camunda:
  bpm:
    enabled: true
    admin-user:
      id: admin
      password: 123456
      firstName: admin
    job-execution:
      enabled: false
    filter:
      create: All tasks
    id-generator: snowFlakeIdGenerator
    auto-deployment-enabled: true
spring:
  jersey:
    application-path: /engine-rest
  datasource:
    name: camundaBpmDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/camunda
      username: postgres
      password: root
      filters: stat,wall,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # 设置ip白名单
        allow: 127.0.0.1,172.16.96.129
        # 设置ip黑名单，优先级高于白名单
        deny:
        # 设置控制台管理用户
        login-username: root
        login-password: root
        # 是否可以重置数据
        reset-enable: false
        # 开启druid监控页面
        enabled: true
  resources:
    static-locations: ["classpath:/templates","classpath:/resources","classpath:/static","classpath:/public"]
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
